### ISSUE TITLE
Naming conventions/different repos per device

### ISSUE THREAD

**Issue by stylesuxx** [fpv-wtf/opkg-repo#2]
I think it would be nice to either have a naming convention that indicates on which devices the packages can be use - or separate repositories for the devices.

* `all`: works on airunit and goggle
* `goggle`: only works on goggle (for example LED related functionality)
* `airunit`: only works on airunit (for example msp OSD part for goggles)

**Comment by j005u** [comment]
Additonal thought here:
Is it too early to think about separate stable(, beta?) and snapshot repos, so people can choose to either be in known good land or live on the edge?

**Comment by j005u** [comment]
We discussed that snapshot repos should be hosted by package devs. We provide everything that is needed to get started.

On another note, I think we could also do a mixed repo, but use architectures instead for this purpose. So we can actually use that to differentiate between pigeon-glasses, pigeon-airside, pigeon-all and entware's armv7-3.8. Architectures allow you to set a preference order, so it would make sense to have device-specific, all, entware in descending order.

**Comment by j005u** [comment]
The plan is to use package architecture for this.

pigeon-all
pigeon-airside
pigeon-glasses

Needs modifications to opkg.conf during setup. Right now the latter is patched by install scripts, we should probably use some way of managing it with a package also?

**Comment by stylesuxx** [comment]
Makes sense - so we basically need two packages in order to replace `opkg.conf` with the proper config for airside and glasses. Or should this be one package that "dynamically" updates `opkg.conf`?

**Comment by stylesuxx** [comment]
#8 adds the package to manipulate `opkg.conf` and adds custom arch depending on detected device.
